# Generated by Django 4.2.16 on 2024-11-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variant',
            name='variant',
            field=models.CharField(max_length=200),
        ),
    ]
