# Generated by Django 4.2.16 on 2024-11-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testlar', '0002_test_public_alter_variant_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='savol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='testlar.question'),
        ),
    ]
